name: web-development-sandbox
recipe: lamp

config:
  via: apache:2.4
  database: mariadb:10.11
  composer_version: '2'
  php: '8.3'
  webroot: web
  cache: none
  xdebug: true
  config:
    php: .vscode/php.ini

services:
  appserver:
    overrides:
      environment:
        ENVIRONMENT: "local"
        PHP_IDE_CONFIG: "serverName=appserver"
  phpmyadmin:
    type: phpmyadmin

env_file:
  - .vscode/lando.env

# Lando version.
version: 3.20.8